#!/usr/bin/env python3
"""refresh_snapshot_md.py -- rewrite the numeric tables in the golden .md snapshots
from the committed .json goldens.

Usage:  python3 tests/golden-snapshots/refresh_snapshot_md.py [--check]

        --check  exit nonzero if any table is stale instead of rewriting (CI-friendly)

WHY. Each golden_*.json has a companion golden_*_snapshot_*.md whose tables were
maintained BY HAND. That is a standing drift hazard: when the RNG swap (TODO section R)
changed every count, the .json files were regenerated by their generators but the .md
tables had no generator at all, so they would silently have kept displaying mulberry32
numbers next to xoshiro128** data. The prose in each .md is the valuable part (provenance,
history, caveats) and is preserved untouched -- only the pipe-table ROWS are rebuilt.

Contract: this script NEVER invents numbers. Every cell is read from the .json, formatted
to the column's existing precision, and written back. Rows are emitted in the .json's own
result order, so a reordered matrix shows up as a reordered table rather than a silent
mismatch.
"""
import json, re, sys, os

HERE = os.path.dirname(os.path.abspath(__file__))
CHECK = "--check" in sys.argv

GEOM_LABEL = {"top-base_faces": "Cloud top/base faces only",
              "all_faces": "Cloud top/base/side faces"}


def f6(x):
    return f"{x:.6f}"


def frac_count(frac, count):
    return f"{frac:.6f} ({count})"


def legacy_rows(results, illum):
    """v5.4.0 matrix: one section per illumination mode, 14 columns."""
    out = []
    for r in results:
        if r["illum"] != illum:
            continue
        out.append("| " + " | ".join([
            f"{r['theta0_deg']:.0f}°",
            f"{r['As']:.2f}",
            GEOM_LABEL.get(r["obsGeom"], r["obsGeom"]),
            frac_count(r["Rfrac"], r["Rcount"]),
            frac_count(r["Tfrac"], r["Tcount"]),
            frac_count(r["Acloud"], r["Acloud_count"]),
            frac_count(r["Sfrac"], r["Scount"]),
            frac_count(r["Tterm"], r["Tterm_count"]),
            f6(r["closure"]),
            f6(r["EdownSfc"]),
            f6(r["EupSfc"]),
            frac_count(r["netSfcAbs"], r["netSfcAbsCount"]),
            f"{r['meanScat']:.4f}",
            f"{r['meanPath']:.4f}",
        ]) + " |")
    return out


def domain_rows(results, periodic):
    """Domain-wide budget: one row per RUN (geometry-independent), so take the first
    observation geometry only -- the domain block is identical across geometries."""
    out, seen = [], set()
    for r in results:
        key = (r["M"], r["theta0_deg"], r["As"])
        if key in seen:
            continue
        seen.add(key)
        d = r["domain"]
        rc, tc, ac = d["R_components"], d["T_components"], d["A_components"]
        cells = [
            f"{r['M']}",
            f"{d['cloud_fraction']:.4f}",
            f"{r['theta0_deg']:.0f}",
            f"{r['As']:g}",
            frac_count(d["R_domain"], d["R_domain_count"]),
            frac_count(d["T_domain"], d["T_domain_count"]),
            f6(d["A_cloud"]),
            f6(d["closure_R_T_Acloud"]),
            f"{rc['cloudTop']}/{rc['cloudSide']}/{rc['clearDirect']}/{rc['clearViaCloud']}",
            f"{tc['viaBase']}/{tc['viaSide']}/{tc['clearDirect']}",
        ]
        if periodic:
            # wrapCapped lives in rawStats; it is a periodic-boundary-only safety counter.
            cells.append(str(r.get("rawStats", {}).get("wrapCapped", 0)))
        out.append("| " + " | ".join(cells) + " |")
    return out


def obsgeom_rows(results):
    out = []
    for r in results:
        out.append("| " + " | ".join([
            f"{r['M']}",
            f"{r['theta0_deg']:.0f}",
            f"{r['As']:g}",
            r["obsGeom"],
            frac_count(r["Rfrac"], r["Rcount"]),
            frac_count(r["Tfrac"], r["Tcount"]),
            f6(r["Acloud"]),
            frac_count(r["Sfrac"], r["Scount"]),
            f6(r["closure"]),
        ]) + " |")
    return out


def replace_table(text, header_marker, new_rows, md_path):
    """Replace the data rows of the pipe table that follows header_marker.

    Located by the table's '|---|' separator line, then every consecutive following line
    starting with '|' is the old body. Fails loudly rather than guessing if the anchor or
    the separator is missing -- a silently skipped table is the exact failure this script
    exists to prevent.
    """
    i = text.find(header_marker)
    if i < 0:
        sys.exit(f"{md_path}: anchor not found: {header_marker!r}")
    sep = re.search(r"^\|[-| ]+\|$", text[i:], re.M)
    if not sep:
        sys.exit(f"{md_path}: no table separator after {header_marker!r}")
    start = i + sep.end() + 1
    end = start
    while end < len(text):
        nl = text.find("\n", end)
        if nl < 0:
            nl = len(text)
        line = text[end:nl]
        if not line.startswith("|"):
            break
        end = nl + 1
    return text[:start] + "\n".join(new_rows) + "\n" + text[end:]


def process(md_name, json_name, build):
    md_path = os.path.join(HERE, md_name)
    results = json.load(open(os.path.join(HERE, json_name)))["results"]
    text = original = open(md_path).read()
    for marker, rows in build(results):
        text = replace_table(text, marker, rows, md_path)
    if text == original:
        print(f"  up to date : {md_name}")
        return False
    if CHECK:
        print(f"  STALE      : {md_name}")
        return True
    open(md_path, "w").write(text)
    print(f"  rewritten  : {md_name}")
    return True


def legacy_build(results):
    return [("## Illumination: Centered (point source) (`center`)", legacy_rows(results, "center")),
            ("## Illumination: Uniform cloud top (`top`)", legacy_rows(results, "top")),
            ("## Illumination: Uniform cloud top + sunward side (`top_side`)", legacy_rows(results, "top_side"))]


def ud_build(results):
    return [("## Domain-wide budget (geometry-independent)", domain_rows(results, periodic=False)),
            ("## Observation-geometry budgets (R/T/A/S per dropdown)", obsgeom_rows(results))]


def per_build(results):
    return [("## Domain-wide budget (geometry-independent)", domain_rows(results, periodic=True)),
            ("## Observation-geometry budgets (R/T/A/S per dropdown)", obsgeom_rows(results))]


print("Refreshing golden .md tables from .json" + (" (--check)" if CHECK else ""))
changed = False
changed |= process("golden_snapshot_v5.4.0.md", "golden_v5.4.0.json", legacy_build)
changed |= process("golden_ud_snapshot_v6.0-phase2.md", "golden_ud_v6.0-phase2.json", ud_build)
changed |= process("golden_periodic_snapshot_v6.0-phase3.md",
                   "golden_periodic_v6.0-phase3.json", per_build)
if CHECK and changed:
    sys.exit("\nSTALE: .md tables disagree with the .json goldens. Run without --check.")
print("done")
